export enum Models {
  KiloAutoFree = "kilo-auto/free",
  AnthropicClaudeOpus46 = "anthropic/claude-opus-4.6",
  AnthropicClaudeSonnet46 = "anthropic/claude-sonnet-4.6",
  OpenAIGPT53Codex = "openai/gpt-5.3-codex",
  XaiGrok46 = "x-ai/grok-4.6",
  OpenRouterClaudeSonnet46 = "openrouter/anthropic/claude-sonnet-4.6",
  OpenRouterGPT55 = "openrouter/openai/gpt-5.5",
  OpenRouterGemini38Flash = "openrouter/google/gemini-3.8-flash",
  OpenRouterGrok47 = "openrouter/x-ai/grok-4.7",
  StepFunStep37FlashFree = "stepfun/step-3.7-flash:free",
  PoolsideLagunaS21Free = "poolside/laguna-s-2.1:free",
  PoolsideLagunaXS21Free = "poolside/laguna-xs-2.1:free",
  NvidiaNemotron3UltraFree = "nvidia/nemotron-3-ultra-550b-a55b:free",
  TencentHy3Free = "tencent/hy3:free",
  OpenRouterFree = "openrouter/free",
  OpenRouterNemotron3UltraFree = "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free",
  OpenRouterSpaceBunnyAlpha = "openrouter/stealth/space-bunny-alpha",
  OpenRouterLing30FlashFinFree = "openrouter/inclusionai/ling-3.0-flash-fin:free",
  OpenRouterLagunaS21Free = "openrouter/poolside/laguna-s-2.1:free",
  OpenRouterDots3NotePreviewFree = "openrouter/dots-studio/dots-3-note-preview:free",
  OpenRouterNemotron35LightningFree = "openrouter/nvidia/nemotron-3.5-lightning:free",
  OpenRouterNexN25ProFree = "openrouter/nex-agi/nex-n2.5-pro:free",
  OpenRouterInklingFree = "openrouter/thinkingmachines/inkling:free",
  OpenRouterNemotron3SuperFree = "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
  OpenRouterLing30FlashSanteFree = "openrouter/inclusionai/ling-3.0-flash-sante:free",
  OpenRouterNexN25MiniFree = "openrouter/nex-agi/nex-n2.5-mini:free",
  OpenRouterInklingSmallFree = "openrouter/thinkingmachines/inkling-small:free",
  OpenRouterNorthMiniCodeFree = "openrouter/cohere/north-mini-code:free",
  OpenRouterLagunaXS21Free = "openrouter/poolside/laguna-xs-2.1:free",
  OpenRouterQwen3827bFree = "openrouter/qwen/qwen3.8-27b:free",
}

export const DEFAULT_MODEL = Models.KiloAutoFree;

export const OPENROUTER_MODEL_PREFIX = "openrouter/";

export const SUPPORTED_MODELS: string[] = [
  Models.KiloAutoFree,
  Models.AnthropicClaudeOpus46,
  Models.AnthropicClaudeSonnet46,
  Models.OpenAIGPT53Codex,
  Models.XaiGrok46,
  Models.OpenRouterClaudeSonnet46,
  Models.OpenRouterGPT55,
  Models.OpenRouterGemini38Flash,
  Models.OpenRouterGrok47,
  Models.StepFunStep37FlashFree,
  Models.PoolsideLagunaS21Free,
  Models.PoolsideLagunaXS21Free,
  Models.NvidiaNemotron3UltraFree,
  Models.TencentHy3Free,
  Models.OpenRouterFree,
  Models.OpenRouterNemotron3UltraFree,
  Models.OpenRouterSpaceBunnyAlpha,
  Models.OpenRouterLing30FlashFinFree,
  Models.OpenRouterLagunaS21Free,
  Models.OpenRouterDots3NotePreviewFree,
  Models.OpenRouterNemotron35LightningFree,
  Models.OpenRouterNexN25ProFree,
  Models.OpenRouterInklingFree,
  Models.OpenRouterNemotron3SuperFree,
  Models.OpenRouterLing30FlashSanteFree,
  Models.OpenRouterNexN25MiniFree,
  Models.OpenRouterInklingSmallFree,
  Models.OpenRouterNorthMiniCodeFree,
  Models.OpenRouterLagunaXS21Free,
  Models.OpenRouterQwen3827bFree,
];

export const MODEL_NAMES: Record<string, string> = {
  [Models.KiloAutoFree]: "Kilo Auto Free",
  [Models.AnthropicClaudeOpus46]: "Claude Opus 4.6",
  [Models.AnthropicClaudeSonnet46]: "Claude Sonnet 4.6",
  [Models.OpenAIGPT53Codex]: "GPT-5.3 Codex",
  [Models.XaiGrok46]: "Grok 4.6",
  [Models.OpenRouterClaudeSonnet46]: "Claude Sonnet 4.6 (OpenRouter)",
  [Models.OpenRouterGPT55]: "GPT-5.5 (OpenRouter)",
  [Models.OpenRouterGemini38Flash]: "Gemini 3.8 Flash (OpenRouter)",
  [Models.OpenRouterGrok47]: "Grok 4.7 (OpenRouter)",
  [Models.StepFunStep37FlashFree]: "Step 3.7 Flash (Free)",
  [Models.PoolsideLagunaS21Free]: "Laguna S 2.1 (Free)",
  [Models.PoolsideLagunaXS21Free]: "Laguna XS 2.1 (Free)",
  [Models.NvidiaNemotron3UltraFree]: "Nemotron 3 Ultra (Free)",
  [Models.TencentHy3Free]: "Tencent Hy3 (Free)",
  [Models.OpenRouterFree]: "OpenRouter Free Router",
  [Models.OpenRouterNemotron3UltraFree]: "Nemotron 3 Ultra (OpenRouter Free)",
  [Models.OpenRouterSpaceBunnyAlpha]: "Space Bunny Alpha (Free)",
  [Models.OpenRouterLing30FlashFinFree]: "Ling 3.0 Flash Fin (Free)",
  [Models.OpenRouterLagunaS21Free]: "Laguna S 2.1 (OpenRouter Free)",
  [Models.OpenRouterDots3NotePreviewFree]: "Dots3-Note Preview (Free)",
  [Models.OpenRouterNemotron35LightningFree]: "Nemotron 3.5 Lightning (Free)",
  [Models.OpenRouterNexN25ProFree]: "Nex-N2.5-Pro (Free)",
  [Models.OpenRouterInklingFree]: "Inkling (Free)",
  [Models.OpenRouterNemotron3SuperFree]: "Nemotron 3 Super (Free)",
  [Models.OpenRouterLing30FlashSanteFree]: "Ling 3.0 Flash Sante (Free)",
  [Models.OpenRouterNexN25MiniFree]: "Nex-N2.5-Mini (Free)",
  [Models.OpenRouterInklingSmallFree]: "Inkling Small (Free)",
  [Models.OpenRouterNorthMiniCodeFree]: "North Mini Code (Free)",
  [Models.OpenRouterLagunaXS21Free]: "Laguna XS 2.1 (OpenRouter Free)",
  [Models.OpenRouterQwen3827bFree]: "Qwen3.8 27B (Free)",
};

export const TEST_PROMPTS = [
  "Generate a Next.js app that allows to list and search Pokemons",
  'Create a `golang` server that responds with "Hello World" to any request',
];
